steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/seo-app/backend-server'
      - '.'
images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/seo-app/backend-server'
